import { CashFlowStatement } from "./types";

/** how long we trust a snapshot (1 week) */
export const CACHE_TTL_MS = 60 * 24 * 7 * 60 * 1_000;

export const cashFlowKeyOrder: ReadonlyArray<keyof CashFlowStatement> = [
  "symbol",
  "date",
  "reportedCurrency",
  "cik",
  "fillingDate",
  "acceptedDate",
  "calendarYear",
  "period",
  "netIncome",
  "depreciationAndAmortization",
  "deferredIncomeTax",
  "stockBasedCompensation",
  "changeInWorkingCapital",
  "accountsReceivables",
  "inventory",
  "accountsPayables",
  "otherWorkingCapital",
  "otherNonCashItems",
  "netCashProvidedByOperatingActivities",
  "investmentsInPropertyPlantAndEquipment",
  "acquisitionsNet",
  "purchasesOfInvestments",
  "salesMaturitiesOfInvestments",
  "otherInvestingActivites",
  "netCashUsedForInvestingActivites",
  "debtRepayment",
  "commonStockIssued",
  "commonStockRepurchased",
  "dividendsPaid",
  "otherFinancingActivites",
  "netCashUsedProvidedByFinancingActivities",
  "effectOfForexChangesOnCash",
  "netChangeInCash",
  "cashAtEndOfPeriod",
  "cashAtBeginningOfPeriod",
  "operatingCashFlow",
  "capitalExpenditure",
  "freeCashFlow",
  "link",
  "finalLink",
];
